"""
state.py
---------
Defines the shared state that flows through the LangGraph
CRAG pipeline. Every node reads from and writes to this state.

Think of it as the "baton" passed between nodes in a relay race.
Each node can read any field and update any field.

State fields:
    query           : Original user question
    rewritten_query : Query after rewriting (if ambiguous retrieval)
    documents       : Retrieved chunks from FAISS or web search
    generation      : Final generated answer
    grade           : Overall retrieval grade (relevant/ambiguous/irrelevant)
    document_grades : Individual grade for each retrieved document
    web_search_used : Whether Tavily web search fallback was triggered
    retry_count     : How many times we've retried (max 3 to prevent loops)
    hallucination   : Whether hallucination was detected in the answer
    source          : Where final context came from (faiss/web/mixed)
    error           : Any error message if something goes wrong
"""

from typing import TypedDict


# ── Document Schema ───────────────────────────────────────────────────────────

class Document(TypedDict):
    """
    A single retrieved document chunk with its metadata.
    Used in the documents list inside CRAGState.
    """
    chunk_id  : str          # e.g. "2401.15884_chunk_3"
    arxiv_id  : str          # e.g. "2401.15884"
    text      : str          # The actual chunk text
    score     : float        # Similarity score from FAISS (0-1)
    title     : str          # Paper title
    authors   : list[str]    # List of author names
    published : str          # Publication date e.g. "2024-01-15"
    url       : str          # arXiv URL
    abstract  : str          # Paper abstract
    grade     : str          # Relevance grade: "relevant"/"ambiguous"/"irrelevant"
    source    : str          # Where this doc came from: "faiss" or "web"


# ── Main State Schema ─────────────────────────────────────────────────────────

class CRAGState(TypedDict):
    """
    The complete state passed between all nodes in the CRAG pipeline.

    LangGraph passes this dict from node to node.
    Each node receives the full state, does its work,
    and returns a dict of only the fields it wants to update.
    LangGraph merges the update back into the state automatically.

    The Annotated[list, operator.add] type on documents means
    LangGraph will APPEND to the list rather than replace it
    when a node returns new documents. This is important for
    combining FAISS results with web search results.
    """

    # ── Input ──────────────────────────────────────────────────────────────
    query: str
    # The original user question. Set once at the start, never changed.

    # ── Retrieval ──────────────────────────────────────────────────────────
    rewritten_query: str
    # If the grader decides retrieval was AMBIGUOUS, the rewriter
    # produces an improved version of the query stored here.
    # The retriever uses this on retry instead of the original query.

    documents: list[Document]
    # List of retrieved document chunks.

    # The clean, filtered list specifically for the generator (accumulates)
    relevant_documents: list[Document]

    # ── Grading ────────────────────────────────────────────────────────────
    grade: str
    # Overall retrieval quality decision made by the grader node.
    # One of: "relevant" | "ambiguous" | "irrelevant"
    # This is what the graph's conditional edges use to decide
    # which node to run next.

    document_grades: list[dict]
    # Per-document grading results from the grader node.
    # Each entry is:
    # {
    #   "chunk_id": str,
    #   "grade": "relevant" | "ambiguous" | "irrelevant",
    #   "reasoning": str
    # }

    # ── Generation ─────────────────────────────────────────────────────────
    generation: str
    # The final answer generated by the generator node.
    # Includes inline citations pointing back to source documents.

    # ── Hallucination Check ────────────────────────────────────────────────
    hallucination: bool
    # Set by the hallucination checker node.
    # True  = answer contains claims not supported by retrieved docs
    # False = answer is grounded in the retrieved context

    hallucination_reasoning: str
    # Explanation from the hallucination checker about why
    # it flagged (or cleared) the answer.

    # ── Control Flow ───────────────────────────────────────────────────────
    retry_count: int
    # Tracks how many retrieval attempts have been made.
    # Incremented each time the rewriter sends us back to retrieval.
    # Hard limit of 3 retries prevents infinite loops.

    web_search_used: bool
    # True if the Tavily web search fallback was triggered.
    # Used for logging and evaluation — tells us how often
    # the local knowledge base was insufficient.

    source: str
    # Where the final context came from.
    # One of: "faiss" | "web" | "mixed"
    # "mixed" = both FAISS and web search contributed documents.

    # ── Error Handling ─────────────────────────────────────────────────────
    error: str
    # If any node encounters an unrecoverable error, it stores
    # a message here. The graph checks this to short-circuit
    # to a safe fallback response instead of crashing.

    # ── Latency Metrics ────────────────────────────────────────────────────
    retrieval_ms: float
    # Cumulative time spent on FAISS retrieval search calls in milliseconds.

    generation_ms: float
    # Time spent on final LLM answer generation in milliseconds.


# ── Initial State Factory ─────────────────────────────────────────────────────

def create_initial_state(query: str) -> CRAGState:
    """
    Create a fresh initial state for a new user query.

    All fields are set to safe default values.
    Only `query` is provided by the caller.

    Args:
        query: The user's question

    Returns:
        A fully initialised CRAGState dict
    """
    if not query or not isinstance(query, str):
        raise ValueError("Query must be a non-empty string")

    return CRAGState(
        query                   = query.strip(),
        rewritten_query         = "",
        documents               = [],
        relevant_documents      = [],
        grade                   = "",
        document_grades         = [],
        generation              = "",
        hallucination           = False,
        hallucination_reasoning = "",
        retry_count             = 0,
        web_search_used         = False,
        source                  = "faiss",
        error                   = "",
        retrieval_ms            = 0.0,
        generation_ms           = 0.0,
    )



# ── Grade Constants ───────────────────────────────────────────────────────────
# Use these constants throughout the pipeline instead of raw strings
# to avoid typos and make the code easier to read.

GRADE_RELEVANT   = "relevant"
GRADE_AMBIGUOUS  = "ambiguous"
GRADE_IRRELEVANT = "irrelevant"

SOURCE_FAISS  = "faiss"
SOURCE_WEB    = "web"
SOURCE_MIXED  = "mixed"

MAX_RETRIES = 3
